<?php

/**
 * OWWA export cell references derived from storage/app/templates/*.xls analysis.
 * Regenerate template-structure.txt after replacing templates:
 *   php artisan owwa:analyze-templates
 */
return [

    'RIS' => [
        'template' => 'requisition/Appendix 63 - RIS.xls',
        'header' => [
            'entity_name' => ['cell' => 'A6', 'label' => 'Entity Name : '],
            'fund_cluster' => ['cell' => 'G6', 'label' => 'Fund Cluster : '],
            'division' => ['cell' => 'A8', 'label' => 'Division : '],
            'responsibility_center_code' => ['cell' => 'F8', 'label' => 'Responsibility Center Code : '],
            'office' => ['cell' => 'A9', 'label' => 'Office : '],
            'ris_no' => ['cell' => 'F9', 'label' => 'RIS No. : '],
            'purpose' => ['cell' => 'A32', 'label' => '   Purpose: '],
        ],
        'detail' => [
            'start_row' => 12,
            'max_rows' => 19,
            'style_row' => 12,
            'highest_column' => 'H',
            'columns' => [
                'stock_no' => 'A',
                'unit' => 'B',
                'description' => 'C',
                'quantity' => 'D',
                'stock_yes' => 'E',
                'stock_no_col' => 'F',
                'issue_quantity' => 'G',
                'issue_remarks' => 'H',
            ],
            'column_types' => [
                'A' => 'mark',
                'B' => 'mark',
                'C' => 'mark',
                'D' => 'qty',
                'E' => 'mark',
                'F' => 'mark',
                'G' => 'qty',
                'H' => 'mark',
            ],
        ],
        'signatures' => [
            'requested_by' => 'C37',
            'approved_by' => 'D37',
        ],
    ],

    'RSMI' => [
        'template' => 'Consumable/Issuances/Appendix 64 - RSMI.xls',
        'header' => [
            'entity_name' => ['cell' => 'A6', 'label' => 'Entity Name: '],
            'serial_no' => ['cell' => 'G6', 'label' => 'Serial No.: '],
            'fund_cluster' => ['cell' => 'A7', 'label' => 'Fund Cluster: '],
            'date' => ['cell' => 'G7', 'label' => 'Date: '],
        ],
        'detail' => [
            'start_row' => 12,
            'end_row' => 32,
            'template_detail_rows' => 21,
            'expand_insert_before_row' => 33,
            'max_rows' => 200,
            'recap_start_row' => 36,
            'recap_end_row' => 51,
            'style_row' => 12,
            'highest_column' => 'H',
            'columns' => [
                'ris_no' => 'A',
                'responsibility_center' => 'B',
                'stock_no' => 'C',
                'item' => 'D',
                'unit' => 'E',
                'quantity' => 'F',
                'unit_cost' => 'G',
                'amount' => 'H',
            ],
            'column_types' => [
                'A' => 'reference',
                'B' => 'text',
                'C' => 'text',
                'D' => 'text',
                'E' => 'text',
                'F' => 'qty',
                'G' => 'unit_cost',
                'H' => 'amount',
            ],
            'wrap_text_columns' => ['A', 'B', 'D'],
            'min_wrap_lines_for_expansion' => 2,
            'uniform_data_row_height' => true,
        ],
        'signatures' => [
            'custodian' => 'A52',
            'accounting_staff' => 'F52',
            'posted_date' => 'H52',
        ],
        'signature_line_row' => 52,
        'signature_line_columns' => ['A', 'F', 'H'],
        'signature_line_placeholders' => [
            'A' => '_____________________________________________',
            'F' => '__________________________',
            'H' => '______________',
        ],
    ],

    'PAR' => [
        'template' => 'ppe/Issuances/Appendix 71 - PAR.xls',
        'header' => [
            'entity_name' => ['cell' => 'A6', 'label' => 'Entity Name : '],
            'fund_cluster' => ['cell' => 'A7', 'label' => 'Fund Cluster:  '],
            'par_no' => ['cell' => 'E7', 'label' => 'PAR No.: '],
        ],
        'detail' => [
            'start_row' => 11,
            'template_detail_rows' => 30,
            'expand_insert_before_row' => 44,
            'max_rows' => 200,
            'style_row' => 11,
            'highest_column' => 'F',
            'columns' => [
                'quantity' => 'A',
                'unit' => 'B',
                'description' => 'C',
                'property_number' => 'D',
                'date_acquired' => 'E',
                'amount' => 'F',
            ],
            'column_types' => [
                'A' => 'qty',
                'B' => 'text',
                'C' => 'text',
                'D' => 'text',
                'E' => 'date',
                'F' => 'amount',
            ],
        ],
        'signatures' => [
            'received_by_name' => 'A45',
            'issued_by_name' => 'D45',
            'received_by_position' => 'A47',
            'issued_by_position' => 'D47',
            'received_by_date' => 'A49',
            'issued_by_date' => 'D49',
        ],
    ],

    'ICS' => [
        'template' => 'Semi-Expendable/Issuances/Appendix 59 - ICS.xls',
        'header' => [
            'entity_name' => ['cell' => 'A6', 'label' => 'Entity Name: '],
            'fund_cluster' => ['cell' => 'A7', 'label' => 'Fund Cluster : '],
            'ics_no' => ['cell' => 'G7', 'label' => 'ICS No : '],
        ],
        'detail' => [
            'start_row' => 12,
            'template_detail_rows' => 30,
            'expand_insert_before_row' => 44,
            'max_rows' => 200,
            'style_row' => 12,
            'highest_column' => 'H',
            'columns' => [
                'quantity' => 'A',
                'unit' => 'B',
                'unit_cost' => 'C',
                'total_cost' => 'D',
                'description' => 'E',
                'inventory_item_no' => 'G',
                'estimated_useful_life' => 'H',
            ],
            'column_types' => [
                'A' => 'qty',
                'B' => 'text',
                'C' => 'unit_cost',
                'D' => 'amount',
                'E' => 'text',
                'G' => 'text',
                'H' => 'text',
            ],
        ],
        'signatures' => [
            'received_from_name' => 'A46',
            'received_by_name' => 'F46',
            'received_from_position' => 'A48',
            'received_by_position' => 'F48',
            'received_from_date' => 'A50',
            'received_by_date' => 'F50',
        ],
    ],

    'PTR' => [
        'template' => 'Appendix 76 - PTR.xlsx',
        'header' => [
            'entity_name' => ['cell' => 'A6', 'label' => 'Entity Name : '],
            'fund_cluster' => ['cell' => 'G6', 'label' => 'Fund Cluster : '],
            'from_accountable' => ['cell' => 'A8', 'label' => 'From Accountable Officer/Agency/Fund Cluster :  '],
            'ptr_no' => ['cell' => 'H8', 'label' => 'PTR No. :  '],
            'to_accountable' => ['cell' => 'A9', 'label' => 'To Accountable Officer/Agency/Fund Cluster : '],
            'date' => ['cell' => 'H9', 'label' => 'Date :  '],
        ],
        'detail' => [
            'start_row' => 18,
            'columns' => [
                'date_acquired' => 'A',
                'property_no' => 'B',
                'description' => 'D',
                'amount' => 'H',
                'condition' => 'I',
            ],
        ],
        // Checkbox cells left of the printed labels (C13/F13/C14/F14).
        'transfer_type_marks' => [
            'donation' => 'B13',
            'relocate' => 'E13',
            'reassignment' => 'B14',
            'others' => 'E14',
        ],
        'transfer_type_others_label' => 'F14',
        'signatures' => [
            'reason' => 'A44',
            'approved_name' => 'B53',
            'released_name' => 'F53',
            'received_name' => 'H53',
            'approved_designation' => 'B54',
            'released_designation' => 'F54',
            'received_designation' => 'H54',
            'approved_date' => 'B55',
            'released_date' => 'F55',
            'received_date' => 'H55',
        ],
    ],

    'PC' => [
        'template' => 'ppe/Accquisition/Appendix 69 - PC.xls',
        'header' => [
            'entity_name' => ['cell' => 'B6', 'label' => 'Entity Name : '],
            'fund_cluster' => ['cell' => 'I6', 'label' => 'Fund Cluster: '],
            'property_number' => ['cell' => 'I9', 'label' => 'Property Number:'],
            'description' => ['cell' => 'B10', 'label' => 'Description : '],
        ],
        'ledger' => [
            'start_row' => 12,
            'blank_style_rows' => 5,
            'max_rows' => 40,
            'style_row' => 12,
            'clear_to_row' => 500,
            'columns' => [
                'date' => 'B',
                'reference' => 'C',
                'receipt_qty' => 'D',
                'issue_qty' => 'E',
                'office_officer' => 'F',
                'balance_qty' => 'H',
                'amount' => 'I',
                'remarks' => 'J',
            ],
            'column_types' => [
                'B' => 'date',
                'C' => 'reference',
                'D' => 'qty',
                'E' => 'qty',
                'F' => 'text',
                'H' => 'balance',
                'I' => 'amount',
                'J' => 'text',
            ],
            'alignments' => [
                'B' => 'center',
                'C' => 'left',
                'D' => 'center',
                'E' => 'center',
                'F' => 'left',
                'H' => 'right',
                'I' => 'right',
                'J' => 'left',
            ],
            'wrap_text_columns' => ['C', 'F', 'J'],
            'min_wrap_lines_for_expansion' => 2,
            'uniform_data_row_height' => true,
        ],
    ],

    'ANNEX_A1' => [
        'template' => 'Semi-Expendable/Recording (Stock Levels)/Property-Form-Annex-A.1-Semi-expendable-Property-Card.xlsx',
        'template_sheet' => 'SPC',
        'owwa_header_rows' => 7,
        'item_header_rows' => 5,
        'table_header_rows' => 2,
        'spacer_rows' => 1,
        'header' => [
            'entity_name' => ['cell' => 'A8', 'label' => 'Entity Name : '],
            'fund_cluster' => ['cell' => 'K8', 'label' => 'Fund Cluster: '],
            'property_type' => ['cell' => 'A10', 'label' => 'Semi-expendable Property : '],
            'property_number' => ['cell' => 'K11', 'label' => 'Semi-expendable Property Number: '],
            'description' => ['cell' => 'A12', 'label' => 'Description : '],
        ],
        'ledger' => [
            'start_row' => 15,
            'blank_style_rows' => 5,
            'date_font_size' => 10,
            'max_rows' => 50,
            'style_row' => 15,
            'clear_to_row' => 0,
            'columns' => [
                'date' => 'A',
                'reference' => 'B',
                'receipt_qty' => 'C',
                'unit_cost' => 'D',
                'total_cost' => 'E',
                'receipt_qty_dup' => 'F',
                'item_no' => 'G',
                'issue_qty' => 'H',
                'office_officer' => 'I',
                'balance_qty' => 'J',
                'amount' => 'K',
                'remarks' => 'L',
            ],
            'column_types' => [
                'A' => 'date',
                'B' => 'reference',
                'C' => 'qty',
                'D' => 'unit_cost',
                'E' => 'amount',
                'F' => 'qty',
                'G' => 'text',
                'H' => 'qty',
                'I' => 'text',
                'J' => 'balance',
                'K' => 'amount',
                'L' => 'text',
            ],
            'alignments' => [
                'A' => 'center',
                'B' => 'left',
                'C' => 'center',
                'D' => 'center',
                'E' => 'center',
                'F' => 'center',
                'G' => 'left',
                'H' => 'right',
                'I' => 'left',
                'J' => 'right',
                'K' => 'right',
                'L' => 'left',
            ],
            'wrap_text_columns' => ['B', 'G', 'I', 'L'],
            'min_wrap_lines_for_expansion' => 2,
            'uniform_data_row_height' => true,
        ],
    ],

    'ANNEX_A4' => [
        'template' => 'Semi-Expendable/Property-Form-Annex-A.4-Registry-of-Semi-Expendable-Property-Issued.xlsx',
        // Master sheet only (RegSPI). Remove property-class tabs from the template; export clones one tab per class.
        // After replacing the file under resources/owwa-templates/, run: php artisan owwa:sync-templates
        'template_sheet' => 'RegSPI',
        'header' => [
            'entity_name' => ['cell' => 'A6', 'label' => 'Entity Name: '],
            'fund_cluster' => ['cell' => 'L6', 'label' => 'Fund Cluster : '],
            'property_type' => ['cell' => 'A7', 'label' => 'Semi-Expendable Property: '],
        ],
        'ledger' => [
            'start_row' => 12,
            'blank_style_rows' => 20,
            'max_rows' => 200,
            'style_row' => 12,
            'clear_to_row' => 0,
            'highest_column' => 'O',
            'columns' => [
                'date' => 'A',
                'reference' => 'B',
                'property_number' => 'C',
                'description' => 'D',
                'useful_life' => 'E',
                'issued_qty' => 'F',
                'issued_office' => 'G',
                'returned_qty' => 'H',
                'returned_office' => 'I',
                'reissued_qty' => 'J',
                'reissued_office' => 'K',
                'disposed_qty' => 'L',
                'balance_qty' => 'M',
                'amount' => 'N',
                'remarks' => 'O',
            ],
            'column_types' => [
                'A' => 'date',
                'B' => 'reference',
                'C' => 'text',
                'D' => 'text',
                'E' => 'text',
                'F' => 'qty',
                'G' => 'text',
                'H' => 'qty',
                'I' => 'text',
                'J' => 'qty',
                'K' => 'text',
                'L' => 'qty',
                'M' => 'balance',
                'N' => 'amount',
                'O' => 'text',
            ],
            'wrap_text_columns' => ['B', 'C', 'D', 'G', 'I', 'K', 'O'],
            'min_wrap_lines_for_expansion' => 2,
            'uniform_data_row_height' => true,
            'min_sample_clear_rows' => 30,
        ],
    ],

    'SC' => [
        'template' => 'Consumable/Stock Levels & Recording/Appendix 58 - SC.xlsx',
        'header' => [
            'entity_name' => ['cell' => 'A6', 'label' => 'Entity Name: '],
            'fund_cluster' => ['cell' => 'F6', 'label' => 'Fund Cluster: '],
            'item' => ['cell' => 'A8', 'label' => 'Item : '],
            'stock_no' => ['cell' => 'F8', 'label' => 'Stock No. : '],
            'description' => ['cell' => 'A9', 'label' => 'Description : '],
            'reorder_point' => ['cell' => 'F9', 'label' => 'Re-order Point : '],
            'unit_of_measurement' => ['cell' => 'A10', 'label' => 'Unit of Measurement : '],
        ],
        'ledger' => [
            'start_row' => 13,
            'blank_style_rows' => 5,
            'max_rows' => 50,
            'style_row' => 13,
            'clear_to_row' => 500,
            'highest_column' => 'G',
            'columns' => [
                'date' => 'A',
                'reference' => 'B',
                'receipt_qty' => 'C',
                'issue_qty' => 'D',
                'issue_office' => 'E',
                'balance_qty' => 'F',
                'days_to_consume' => 'G',
            ],
            'column_types' => [
                'A' => 'date',
                'B' => 'reference',
                'C' => 'qty',
                'D' => 'qty',
                'E' => 'text',
                'F' => 'qty',
                'G' => 'text',
            ],
            'wrap_text_columns' => ['B', 'E', 'G'],
            'min_wrap_lines_for_expansion' => 2,
            'uniform_data_row_height' => true,
        ],
    ],

    'WMR' => [
        'template' => 'Consumable/Disposal/Appendix 65 - WMR.xlsx',
        'header' => [
            'entity_name' => ['cell' => 'A7', 'label' => 'Entity Name : '],
            'fund_cluster' => ['cell' => 'G7', 'label' => 'Fund Cluster : '],
            'place_of_storage' => ['cell' => 'A8', 'label' => 'Place of Storage : '],
            'date' => ['cell' => 'G8', 'label' => 'Date : '],
        ],
        'detail' => [
            'start_row' => 13,
            'columns' => [
                'item_no' => 'A',
                'quantity' => 'B',
                'unit' => 'C',
                'description' => 'D',
                'official_receipt_no' => 'G',
                'sale_date' => 'H',
                'sale_amount' => 'I',
            ],
            'total_cell' => 'I23',
        ],
        'disposal_mode_marks' => [
            'destroyed' => 'C32',
            'sold_private' => 'C33',
            'sold_public' => 'C34',
            'transferred_without_cost' => 'C35',
        ],
        'signatures' => [
            'prepared_by' => 'B25',
            'approved_by' => 'G25',
            'inspected_by' => 'B37',
            'witness' => 'G37',
        ],
    ],

    'RLSDDP' => [
        'template' => 'Appendix 75 - RLSDDP.xls',
        'header' => [
            'entity_name' => ['cell' => 'B6', 'label' => 'Entity Name : '],
            'fund_cluster' => ['cell' => 'G6', 'label' => 'Fund Cluster: '],
            'department_office' => ['cell' => 'B8', 'label' => 'Department/Office : '],
            'rlsddp_no' => ['cell' => 'G8', 'label' => 'RLSDDP No. : '],
            'accountable_officer' => ['cell' => 'B9', 'label' => 'Accountable Officer : '],
            'rlsddp_date' => ['cell' => 'G9', 'label' => 'RLSDDP Date : '],
            'designation' => ['cell' => 'B10', 'label' => 'Designation : '],
            'par_no' => ['cell' => 'G10', 'label' => 'PAR No. : '],
            'par_date' => ['cell' => 'G11', 'label' => 'PAR Date : '],
        ],
        'detail' => [
            'start_row' => 20,
            'columns' => [
                'property_no' => 'B',
                'description' => 'C',
                'acquisition_cost' => 'G',
            ],
        ],
        'extra' => [
            'circumstances' => 'B30',
        ],
        'police' => [
            'yes_mark' => 'C11',
            'station' => 'D11',
            'date' => 'D12',
            'no_mark' => 'C13',
        ],
        'property_status_marks' => [
            'lost' => 'D17',
            'stolen' => 'D18',
            'damaged' => 'F17',
            'destroyed' => 'F18',
        ],
        'gov_id' => [
            'type' => 'B44',
            'number' => 'B45',
            'date_issued' => 'B46',
        ],
        'signatures' => [
            'accountable_officer' => 'B39',
            'noted_by' => 'F39',
            'accountable_date' => 'B41',
            'noted_date' => 'F41',
        ],
    ],

    'IIRUP' => [
        'template' => 'ppe/Disposal/Appendix 74 - IIRUP.xlsx',
        'header' => [
            'as_at' => ['cell' => 'B4', 'label' => 'As at '],
            'entity_name' => ['cell' => 'B6', 'label' => 'Entity Name: '],
            'fund_cluster' => ['cell' => 'P6', 'label' => 'Fund Cluster: '],
            'accountable_officer' => ['cell' => 'B7', 'label' => ''],
            'accountable_designation' => ['cell' => 'F7', 'label' => ''],
            'accountable_station' => ['cell' => 'K7', 'label' => ''],
        ],
        'detail' => [
            'start_row' => 15,
            'max_rows' => 20,
            'style_row' => 15,
            'highest_column' => 'P',
            'count_column' => 'C',
            'columns' => [
                'date_acquired' => 'B',
                'description' => 'C',
                'property_no' => 'D',
                'quantity' => 'E',
                'unit_cost' => 'F',
                'total_cost' => 'G',
                'accumulated_depreciation' => 'H',
                'accumulated_impairment_losses' => 'I',
                'carrying_amount' => 'J',
                'remarks' => 'K',
                'disposal_total' => 'P',
            ],
            'column_types' => [
                'B' => 'date',
                'C' => 'text',
                'D' => 'text',
                'E' => 'qty',
                'F' => 'unit_cost',
                'G' => 'amount',
                'H' => 'amount',
                'I' => 'amount',
                'J' => 'amount',
                'K' => 'text',
                'P' => 'amount',
            ],
            'wrap_text_columns' => ['C', 'D', 'K'],
            'min_wrap_lines_for_expansion' => 2,
            'uniform_data_row_height' => false,
        ],
        'disposal_mode_columns' => [
            'sale' => 'L',
            'transfer' => 'M',
            'destruction' => 'N',
            'others' => 'O',
        ],
        'signatures' => [
            'custodian' => 'C40',
            'approved_by' => 'H40',
            'inspection_officer' => 'L40',
            'witness' => 'Q40',
            'accountable_designation' => 'C42',
            'authorized_designation' => 'H42',
        ],
    ],

    // Annex A.10 — inventory + disposal mode + inspection/witness (no appraised / record of sales).
    'IIRUSP' => [
        'template' => 'Semi-Expendable/Disposal/Annex A.10 - IIRUSP.xlsx',
        'header' => [
            'as_at' => ['cell' => 'B6', 'label' => 'As at '],
            'entity_name' => ['cell' => 'B8', 'label' => 'Entity Name: '],
            'fund_cluster' => ['cell' => 'P8', 'label' => 'Fund Cluster : '],
            // Sample reviewer sheet writes names on row 9 above the printed placeholders.
            'accountable_officer' => ['cell' => 'C9', 'label' => ''],
            'accountable_designation' => ['cell' => 'F9', 'label' => ''],
            'accountable_station' => ['cell' => 'K9', 'label' => ''],
        ],
        'detail' => [
            'start_row' => 17,
            'max_rows' => 20,
            'style_row' => 17,
            'highest_column' => 'P',
            'count_column' => 'C',
            'columns' => [
                'date_acquired' => 'B',
                'description' => 'C',
                'property_no' => 'D',
                'quantity' => 'E',
                'unit_cost' => 'F',
                'total_cost' => 'G',
                'accumulated_depreciation' => 'H',
                'accumulated_impairment_losses' => 'I',
                'carrying_amount' => 'J',
                'remarks' => 'K',
                'disposal_total' => 'P',
            ],
            'column_types' => [
                'B' => 'date',
                'C' => 'text',
                'D' => 'text',
                'E' => 'qty',
                'F' => 'unit_cost',
                'G' => 'amount',
                'H' => 'amount',
                'I' => 'amount',
                'J' => 'amount',
                'K' => 'text',
                'P' => 'amount',
            ],
            'wrap_text_columns' => ['C', 'D', 'K'],
            'min_wrap_lines_for_expansion' => 2,
            'uniform_data_row_height' => false,
        ],
        'disposal_mode_columns' => [
            'sale' => 'L',
            'transfer' => 'M',
            'destruction' => 'N',
            'others' => 'O',
        ],
        'signatures' => [
            'custodian' => 'C45',
            'approved_by' => 'H45',
            'inspection_officer' => 'L45',
            'witness' => 'Q45',
        ],
    ],

    'RPCI' => [
        'template' => 'Consumable/Stock Levels & Recording/Appendix 66 - RPCI.xlsx',
        'header' => [
            'inventory_type' => ['cell' => 'B4', 'label' => ''],
            'count_date' => ['cell' => 'B6', 'label' => 'As at '],
            'fund_cluster' => ['cell' => 'B8', 'label' => 'Fund Cluster : '],
            'accountable_officer' => ['cell' => 'B10', 'label' => 'For which '],
        ],
        'detail' => [
            'start_row' => 15,
            'max_rows' => 21,
            'style_row' => 16,
            'highest_column' => 'K',
            'signature_block_start_row' => 37,
            'template_detail_rows' => 21,
            'continuation_sheet_suffix' => ' Cont.',
            'detail_block_end_row' => 36,
            'columns' => [
                'article' => 'B',
                'description' => 'C',
                'stock_number' => 'D',
                'unit_of_measure' => 'E',
                'unit_value' => 'F',
                'balance_per_card' => 'G',
                'on_hand_count' => 'H',
                'shortage_qty' => 'I',
                'shortage_value' => 'J',
                'remarks' => 'K',
            ],
            'column_types' => [
                'B' => 'text',
                'C' => 'text',
                'D' => 'text',
                'E' => 'text',
                'F' => 'unit_cost',
                'G' => 'qty',
                'H' => 'qty',
                'I' => 'qty',
                'J' => 'amount',
                'K' => 'text',
            ],
            'wrap_text_columns' => ['B', 'C', 'D', 'K'],
            'expandable_wrap_columns' => ['B', 'C', 'D'],
            'max_detail_row_height' => null,
            'max_column_width' => 45,
            'column_width_step' => 2,
            'min_wrap_lines_for_expansion' => 2,
            'uniform_data_row_height' => false,
            'layout_mode' => 'continuous',
            'page' => [
                'block_start_row' => 1,
                'block_row_count' => 40,
                'rows_per_page' => 21,
                'highest_column' => 'K',
            ],
        ],
        'signature_block' => [
            'start_row' => 37,
            'line_row' => 39,
            'columns' => [
                'certified_by' => 'C',
                'approved_by' => 'G',
                'verified_by' => 'K',
            ],
        ],
        'signatures' => [
            'certified_by' => 'C39',
            'approved_by' => 'G39',
            'verified_by' => 'K39',
        ],
    ],

    'RPCPPE' => [
        'template' => 'ppe/Physical Count/Appendix 73 - RPCPPE.xlsx',
        'header' => [
            'inventory_type' => ['cell' => 'C4', 'label' => ''],
            'count_date' => ['cell' => 'C6', 'label' => 'As at '],
            'fund_cluster' => ['cell' => 'C9', 'label' => 'Fund Cluster : '],
            'accountable_officer' => ['cell' => 'C10', 'label' => 'For which '],
        ],
        'detail' => [
            'start_row' => 15,
            'max_rows' => 21,
            'style_row' => 16,
            'highest_column' => 'L',
            'signature_block_start_row' => 36,
            'template_detail_rows' => 21,
            'continuation_sheet_suffix' => ' Cont.',
            'detail_block_end_row' => 35,
            'columns' => [
                'article' => 'C',
                'description' => 'D',
                'property_number' => 'E',
                'unit_of_measure' => 'F',
                'unit_value' => 'G',
                'balance_per_card' => 'H',
                'on_hand_count' => 'I',
                'shortage_qty' => 'J',
                'shortage_value' => 'K',
                'remarks' => 'L',
            ],
            'column_types' => [
                'C' => 'text',
                'D' => 'text',
                'E' => 'text',
                'F' => 'text',
                'G' => 'unit_cost',
                'H' => 'qty',
                'I' => 'qty',
                'J' => 'qty',
                'K' => 'amount',
                'L' => 'text',
            ],
            'wrap_text_columns' => ['C', 'D', 'E', 'L'],
            'expandable_wrap_columns' => ['C', 'D', 'E'],
            'max_detail_row_height' => null,
            'max_column_width' => 45,
            'column_width_step' => 2,
            'min_wrap_lines_for_expansion' => 2,
            'uniform_data_row_height' => false,
            'layout_mode' => 'continuous',
            'page' => [
                'block_start_row' => 1,
                'block_row_count' => 39,
                'rows_per_page' => 21,
                'highest_column' => 'L',
            ],
        ],
        'signature_block' => [
            'start_row' => 36,
            'line_row' => 38,
            'columns' => [
                'certified_by' => 'D',
                'approved_by' => 'G',
                'verified_by' => 'K',
            ],
        ],
        'signatures' => [
            'certified_by' => 'D38',
            'approved_by' => 'G38',
            'verified_by' => 'K38',
        ],
    ],

    'RPCSP' => [
        'template' => 'Semi-Expendable/Physical Count/Inventory-Annex-A.8-RPCSP - REPORT.xlsx',
        'header' => [
            'inventory_type' => ['cell' => 'B5', 'label' => ''],
            'count_date' => ['cell' => 'B7', 'label' => 'As at '],
            'fund_cluster' => ['cell' => 'B9', 'label' => 'Fund Cluster : '],
            'accountable_officer' => ['cell' => 'B10', 'label' => 'For which '],
        ],
        'detail' => [
            // Category sheets reserve B15:K15 for "***nothing to report***"; data starts at row 16.
            'start_row' => 16,
            'max_rows' => 20,
            'style_row' => 16,
            'highest_column' => 'K',
            'signature_block_start_row' => 36,
            'template_detail_rows' => 20,
            'continuation_sheet_suffix' => ' Cont.',
            'detail_block_end_row' => 35,
            'nothing_to_report_row' => 15,
            'columns' => [
                'article' => 'B',
                'description' => 'C',
                'property_number' => 'D',
                'unit_of_measure' => 'E',
                'unit_value' => 'F',
                'balance_per_card' => 'G',
                'on_hand_count' => 'H',
                'shortage_qty' => 'I',
                'shortage_value' => 'J',
                'remarks' => 'K',
            ],
            'column_types' => [
                'B' => 'text',
                'C' => 'text',
                'D' => 'text',
                'E' => 'text',
                'F' => 'unit_cost',
                'G' => 'qty',
                'H' => 'qty',
                'I' => 'qty',
                'J' => 'amount',
                'K' => 'text',
            ],
            'wrap_text_columns' => ['B', 'C', 'D', 'K'],
            'expandable_wrap_columns' => ['B', 'C', 'D'],
            'max_detail_row_height' => null,
            'max_column_width' => 45,
            'column_width_step' => 2,
            'min_wrap_lines_for_expansion' => 2,
            'uniform_data_row_height' => false,
            'layout_mode' => 'continuous',
            'page' => [
                'block_start_row' => 1,
                'block_row_count' => 39,
                'rows_per_page' => 20,
                'highest_column' => 'K',
            ],
        ],
        'signature_block' => [
            'start_row' => 36,
            'line_row' => 38,
            'columns' => [
                'certified_by' => 'C',
                'approved_by' => 'F',
                'verified_by' => 'J',
            ],
        ],
        'signature_block_master' => [
            'start_row' => 50,
            'line_row' => 52,
            'columns' => [
                'certified_by' => 'C',
                'approved_by' => 'F',
                'verified_by' => 'J',
            ],
        ],
        'signatures' => [
            'certified_by' => 'C38',
            'approved_by' => 'F38',
            'verified_by' => 'J38',
        ],
        'signatures_master' => [
            'certified_by' => 'C52',
            'approved_by' => 'F52',
            'verified_by' => 'J52',
        ],
    ],

    'PR' => [
        'template' => 'Consumable/Acquisitions/Appendix 60 - PR.xls',
        'header' => [
            'entity_name' => ['cell' => 'A6', 'label' => 'Entity Name: '],
            'fund_cluster' => ['cell' => 'D6', 'label' => 'Fund Cluster: '],
            'office_section' => [
                // Template keeps "Office/Section :" on A7; value goes on A8 only.
                'cell' => 'A8',
                'label' => '',
                'wrap_rows' => [8],
                'wrap_column' => 'A',
            ],
            'pr_no' => ['cell' => 'C7', 'label' => 'PR No.: '],
            'date' => ['cell' => 'E7', 'label' => 'Date: '],
            'responsibility_center_code' => ['cell' => 'C8', 'label' => 'Responsibility Center Code : '],
            'purpose' => ['cell' => 'A33', 'label' => 'Purpose: '],
        ],
        'detail' => [
            'start_row' => 11,
            'max_rows' => 22,
            'footer_start_row' => 33,
            'continuation_sheet_suffix' => ' Cont.',
            'style_row' => 11,
            'highest_column' => 'F',
            'columns' => [
                'stock_no' => 'A',
                'unit' => 'B',
                'description' => 'C',
                'quantity' => 'D',
                'unit_cost' => 'E',
                'total_cost' => 'F',
            ],
            'column_types' => [
                'A' => 'text',
                'B' => 'text',
                'C' => 'text',
                'D' => 'qty',
                'E' => 'unit_cost',
                'F' => 'amount',
            ],
            'wrap_text_columns' => ['A', 'B', 'C', 'D', 'E', 'F'],
            'min_wrap_lines_for_expansion' => 1,
            'uniform_data_row_height' => true,
        ],
        'signatures' => [
            'requested_by' => 'B39',
            'approved_by' => 'D39',
            'requested_by_designation' => 'B40',
            'approved_by_designation' => 'D40',
        ],
    ],

    'PO' => [
        'template' => 'Consumable/Acquisitions/Appendix 61 - PO.xls',
        'header' => [
            'supplier' => ['cell' => 'A7', 'label' => 'Supplier : '],
            'po_no' => ['cell' => 'D7', 'label' => 'P.O. No. : '],
            'date' => ['cell' => 'D8', 'label' => 'Date : '],
            'address' => ['cell' => 'A8', 'label' => 'Address : '],
            'tin' => ['cell' => 'A9', 'label' => 'TIN : '],
            'mode_of_procurement' => ['cell' => 'D9', 'label' => 'Mode of Procurement : '],
            'place_of_delivery' => ['cell' => 'A13', 'label' => 'Place of Delivery :  '],
            'delivery_term' => ['cell' => 'D13', 'label' => 'Delivery Term : '],
            'date_of_delivery' => ['cell' => 'A14', 'label' => 'Date of Delivery : '],
            'payment_term' => ['cell' => 'D14', 'label' => 'Payment Term : '],
            // Leave template blanks (underscores) for manual completion — never overwrite.
            'fund_cluster' => ['cell' => 'A45', 'label' => 'Fund Cluster : '],
            'funds_available' => ['cell' => 'A46', 'label' => 'Funds Available : '],
            'ors_burs_no' => ['cell' => 'D45', 'label' => 'ORS/BURS No. : '],
            'ors_burs_date' => ['cell' => 'D46', 'label' => 'Date of the ORS/BURS: '],
            'total_amount_in_words' => ['cell' => 'A32', 'label' => ''],
        ],
        'detail' => [
            // Rows 16–30: line items. Row 31: total amount in numbers. Row 32: total amount in words.
            'start_row' => 16,
            'max_rows' => 15,
            'footer_start_row' => 32,
            'total_amount_numbers_row_offset' => -1,
            'continuation_sheet_suffix' => ' Cont.',
            'style_row' => 16,
            'highest_column' => 'F',
            'columns' => [
                'stock_no' => 'A',
                'unit' => 'B',
                'description' => 'C',
                'quantity' => 'D',
                'unit_cost' => 'E',
                'amount' => 'F',
            ],
            'column_types' => [
                'A' => 'text',
                'B' => 'text',
                'C' => 'text',
                'D' => 'qty',
                'E' => 'unit_cost',
                'F' => 'amount',
            ],
            'wrap_text_columns' => ['A', 'B', 'C', 'D', 'E', 'F'],
            'min_wrap_lines_for_expansion' => 2,
            'uniform_data_row_height' => true,
        ],
        'signatures' => [
            'supplier_signatory' => 'A39',
            'authorized_official' => 'D39',
        ],
        'accounting_preserve_cells' => ['A45', 'D45', 'A46', 'D46'],
    ],

    'IAR' => [
        'template' => 'Consumable/Acquisitions/Appendix 62- IAR.xls',
        'header' => [
            'entity_name' => ['cell' => 'A6', 'label' => 'Entity Name : '],
            'fund_cluster' => ['cell' => 'D6', 'label' => 'Fund Cluster : '],
            'supplier' => ['cell' => 'A8', 'label' => ' Supplier : '],
            'iar_no' => ['cell' => 'D8', 'label' => 'IAR No. : '],
            'po_no_date' => ['cell' => 'A9', 'label' => ' PO No./Date : '],
            'date' => ['cell' => 'D9', 'label' => 'Date : '],
            'requisitioning_office' => ['cell' => 'A10', 'label' => ' Requisitioning Office/Dept. : '],
            'invoice_no' => ['cell' => 'D10', 'label' => 'Invoice No. : '],
            'responsibility_center_code' => ['cell' => 'A11', 'label' => ' Responsibility Center Code : '],
            'invoice_date' => ['cell' => 'D11', 'label' => 'Date : '],
            'date_inspected' => ['cell' => 'A28', 'label' => 'Inspection Date : '],
            'date_received' => ['cell' => 'C28', 'label' => 'Receive Date : '],
        ],
        'detail' => [
            'start_row' => 14,
            'max_rows' => 13,
            'footer_start_row' => 27,
            'continuation_sheet_suffix' => ' Cont.',
            'style_row' => 14,
            'highest_column' => 'E',
            'columns' => [
                'stock_no' => 'A',
                'description' => 'B',
                'unit' => 'D',
                'quantity' => 'E',
            ],
            'column_types' => [
                'A' => 'text',
                'B' => 'text',
                'D' => 'text',
                'E' => 'qty',
            ],
            'wrap_text_columns' => ['A', 'B', 'D', 'E'],
            'min_wrap_lines_for_expansion' => 1,
            'uniform_data_row_height' => true,
        ],
        'signatures' => [
            'inspection_officer' => 'A35',
            'supply_custodian' => 'C35',
        ],
    ],

];
