<?php

namespace App\Filament\Resources;

use App\Filament\Concerns\HasOwwaViewModalUrl;
use App\Filament\Resources\AiProcurementRunResource\Actions\AiProcurementRunViewActions;
use App\Filament\Resources\AiProcurementRunResource\Pages;
use App\Filament\Resources\AiProcurementRunResource\RelationManagers\ItemsRelationManager;
use App\Filament\Resources\AiProcurementRunResource\Schemas\AiProcurementRunModalSchema;
use App\Filament\Support\ConfiguresOwwaViewAction;
use App\Models\AiProcurementRun;
use BackedEnum;
use Filament\Actions\Action;
use Filament\Actions\ActionGroup;
use Filament\Facades\Filament;
use Filament\Infolists;
use Filament\Resources\Resource;
use Filament\Support\Icons\Heroicon;
use Filament\Tables;
use Filament\Tables\Table;
use Illuminate\Support\Str;
use UnitEnum;

class AiProcurementRunResource extends Resource
{
    use HasOwwaViewModalUrl;

    protected static ?string $model = AiProcurementRun::class;

    protected static string|UnitEnum|null $navigationGroup = 'Analytics';

    protected static string|BackedEnum|null $navigationIcon = Heroicon::OutlinedClock;

    protected static ?int $navigationSort = 2;

    protected static ?string $navigationLabel = 'Recommendation History';

    protected static ?string $modelLabel = 'AI procurement run';

    protected static ?string $pluralModelLabel = 'AI procurement runs';

    public static function form(\Filament\Schemas\Schema $schema): \Filament\Schemas\Schema
    {
        return $schema;
    }

    public static function infolist(\Filament\Schemas\Schema $schema): \Filament\Schemas\Schema
    {
        return $schema
            ->schema([
                Infolists\Components\ViewEntry::make('run_banner')
                    ->view('filament.resources.ai-procurement-run-resource.partials.run-banner')
                    ->columnSpanFull(),
            ]);
    }

    public static function table(Table $table): Table
    {
        return $table
            ->columns([
                Tables\Columns\TextColumn::make('ran_at')
                    ->label('Generated at')
                    ->dateTime('M d, Y g:i A')
                    ->sortable()
                    ->searchable(),
                Tables\Columns\TextColumn::make('summary')
                    ->label('Summary')
                    ->formatStateUsing(function (?string $state): string {
                        if (! $state) {
                            return '—';
                        }
                        // Strip markdown symbols so the list looks clean
                        $clean = preg_replace('/[#*_`~>]+/', '', $state);
                        $clean = preg_replace('/\s+/', ' ', $clean);

                        return Str::limit(trim((string) $clean), 90);
                    })
                    ->wrap()
                    ->placeholder('—'),
                Tables\Columns\TextColumn::make('items_count')
                    ->label('Items')
                    ->counts('items')
                    ->badge()
                    ->color('info')
                    ->alignCenter(),
                Tables\Columns\TextColumn::make('status')
                    ->badge()
                    ->formatStateUsing(fn (string $state) => match ($state) {
                        'processing' => 'Processing',
                        'failed' => 'Failed',
                        'pending' => 'Pending',
                        'approved' => 'Approved',
                        default => ucfirst($state),
                    })
                    ->color(fn (string $state): string => match ($state) {
                        'processing' => 'warning',
                        'failed' => 'danger',
                        'approved' => 'success',
                        default => 'gray',
                    })
                    ->sortable(),
                Tables\Columns\TextColumn::make('creator.name')
                    ->label('Generated by')
                    ->placeholder('System')
                    ->toggleable(isToggledHiddenByDefault: true),
            ])
            ->defaultSort('ran_at', 'desc')
            ->filters([
                Tables\Filters\SelectFilter::make('status')
                    ->label('Status')
                    ->options([
                        'processing' => 'Processing',
                        'failed' => 'Failed',
                        'pending' => 'Pending',
                        'approved' => 'Approved',
                    ]),
            ])
            ->recordActions([
                ConfiguresOwwaViewAction::make(
                    schema: AiProcurementRunModalSchema::components(),
                    footerActions: AiProcurementRunViewActions::modalFooterActions(),
                    modalWidth: '4xl',
                    extraModalClass: 'owwa-ai-run-modal',
                    modelLabel: AiProcurementRunResource::getModelLabel(),
                ),
                ActionGroup::make([
                    Action::make('archive')
                        ->label('Archive')
                        ->icon(Heroicon::OutlinedArchiveBox)
                        ->color('gray')
                        ->requiresConfirmation()
                        ->modalHeading('Archive AI procurement run')
                        ->modalDescription('This run will be hidden from the active list but kept for history. Use the archive icon view to restore it later.')
                        ->visible(fn (AiProcurementRun $record): bool => ! $record->isArchived())
                        ->action(fn (AiProcurementRun $record) => $record->archive()),
                    Action::make('restore')
                        ->label('Restore')
                        ->icon(Heroicon::OutlinedArrowUturnLeft)
                        ->color('gray')
                        ->requiresConfirmation()
                        ->modalHeading('Restore AI procurement run')
                        ->modalDescription('This run will appear in the active list again.')
                        ->visible(fn (AiProcurementRun $record): bool => $record->isArchived())
                        ->action(fn (AiProcurementRun $record) => $record->restoreFromArchive()),
                ])
                    ->label('Actions')
                    ->icon('heroicon-m-ellipsis-vertical')
                    ->color('gray'),
            ])
            ->recordUrl(null)
            ->recordAction('view')
            ->bulkActions([])
            ->emptyStateHeading('No AI runs yet')
            ->emptyStateDescription('Go to Procurement Recommendations and click "Generate Recommendation" to create your first AI analysis.')
            ->emptyStateIcon('heroicon-o-sparkles')
            ->striped();
    }

    public static function getRelations(): array
    {
        return [
            ItemsRelationManager::class,
        ];
    }

    public static function getPages(): array
    {
        return [
            'index' => Pages\ListAiProcurementRuns::route('/'),
            'view' => Pages\ViewAiProcurementRun::route('/{record}'),
        ];
    }

    public static function canViewAny(): bool
    {
        $user = Filament::auth()->user();

        return $user?->isSupplyCustodian();
    }
}
