<?php

namespace App\Support;

use App\Models\AiProcurementRun;
use Illuminate\Support\Str;

class AiProcurementRunViewPresenter
{
    /**
     * @return array<string, mixed>
     */
    public static function forRecord(AiProcurementRun $record): array
    {
        $record->loadMissing(['creator', 'items']);
        $itemCount = $record->items->count();

        $statusMeta = match ($record->status) {
            'draft' => ['bg' => '#f1f5f9', 'text' => '#475569', 'dot' => '#94a3b8', 'label' => 'Draft'],
            'for_approval' => ['bg' => '#fef3c7', 'text' => '#92400e', 'dot' => '#f59e0b', 'label' => 'For approval'],
            'approved' => ['bg' => '#dcfce7', 'text' => '#166534', 'dot' => '#22c55e', 'label' => 'Approved'],
            'archived' => ['bg' => '#f3f4f6', 'text' => '#6b7280', 'dot' => '#9ca3af', 'label' => 'Archived'],
            default => ['bg' => '#f1f5f9', 'text' => '#475569', 'dot' => '#94a3b8', 'label' => ucfirst((string) $record->status)],
        };

        return [
            'reference' => 'Run #'.$record->id,
            'status' => $statusMeta,
            'meta' => [
                ['label' => 'Generated', 'value' => $record->ran_at?->format('M j, Y g:i A') ?? '—'],
                ['label' => 'Period', 'value' => ($record->period_from?->format('M j') ?? '—').' – '.($record->period_to?->format('M j, Y') ?? '—')],
                ['label' => 'Generated by', 'value' => $record->creator?->name ?? 'System'],
                ['label' => 'Items', 'value' => $itemCount.' '.Str::plural('item', $itemCount)],
            ],
            'items' => self::itemsForRecord($record),
        ];
    }

    /**
     * @return array<int, array{priority: ?string, item_name: ?string, office_name: ?string, suggested_qty: string, reason: ?string}>
     */
    public static function itemsForRecord(AiProcurementRun $record): array
    {
        $record->loadMissing('items');

        return $record->items->map(fn ($item): array => [
            'priority' => $item->priority,
            'item_name' => $item->item_name,
            'office_name' => $item->office_name,
            'suggested_qty' => self::formatSuggestedQty($item->suggested_qty_min, $item->suggested_qty_max),
            'reason' => $item->reason,
        ])->all();
    }

    public static function formatSuggestedQty(?int $min, ?int $max): string
    {
        if ($min === null) {
            return '—';
        }

        if ($max === null || $min === $max) {
            return (string) $min;
        }

        return "{$min}–{$max}";
    }
}
